site_name: Kubernetes Nightmares
repo_name: sonminh18/kubernetes-nightmares
repo_url: https://github.com/sonminh18/kubernetes-nightmares
site_url: https://sonminh18.github.io/kubernetes-nightmares/

use_directory_urls: false

theme:
  name: material
  palette:
    primary: blue
  font:
    text: 'Work Sans'
  logo: assets/img/dracula.png
  favicon: assets/img/favicon.ico
  highlightjs: true

plugins:
  - search
  - markdownextradata: {}

extra_css:
  - assets/css/custom-dracula.css
  - assets/css/custom-extra.css

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences
  - toc:
      permalink: true

copyright: |
  &copy; 2023 <a href="https://github.com/sonminh18"  target="_blank" rel="noopener">Son Nguyen</a>