site_name: Kubernetes Nightmares
repo_name: sonminh18/kubernetes-nightmares
repo_url: https://github.com/sonminh18/kubernetes-nightmares
site_url: https://sonminh18.github.io/kubernetes-nightmares/
copyright: Son Nguyen

use_directory_urls: false

# theme:
#   name: dracula
#   logo: assets/img/dracula.png
#   favicon: assets/img/favicon.ico
#   highlightjs: true
#   hljs_languages:
#     - yaml
#     - python
theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

extra_css:
    - assets/css/custom-dracula.css
    - assets/css/custom-extra.css

markdown_extensions:
  - smarty
  - attr_list

copyright: |
  &copy; 2023 <a href="https://github.com/sonminh18"  target="_blank" rel="noopener">Son Nguyen</a>