site_name: Kubernetes Nightmares
repo_name: sonminh18/kubernetes-nightmares
repo_url: https://github.com/sonminh18/kubernetes-nightmares
site_url: https://sonminh18.github.io/kubernetes-nightmares/
copyright: Son Nguyen

nav:
    - Home: index.md
    - Nightmares:
      - nightmares/network-cni.md
      - nightmares/setup-k8s.md
    - About: about.md

theme:
  name: dracula
  logo: assets/img/dracula.png
  favicon: assets/img/favicon.ico